### ISSUE TITLE
能介绍一下mac的使用方法么

### ISSUE THREAD

**Issue by secret-bamboo** [rin93/majsoul_custom_bgm#3]
难道只能在windos运行么？

**Comment by rin93** [comment]
只要你的系统能装chrome或firefox浏览器就能用，python你可以下个mac版的，这个全平台通用。

**Comment by secret-bamboo** [comment]
我运行的结果是：hudeMacBook-Pro:~ huyongf$ cd '/Users/huyongf/Downloads/majsoul_custom_bgm-master/' && '/usr/local/bin/python'  '/Users/huyongf/Downloads/majsoul_custom_bgm-master/start-server.py'  && echo Exit status: $? && exit 1
-bash: /usr/local/bin/python: is a directory
=-=为什么呢。
